### ISSUE TITLE
Can delete files on a 'read only = yes' share?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/smbd#269]
I have the share below via guest and while i can not copy/create files, i can actually delete files/folders? 

```
[test]
	path = /mnt/sda
	create mask = 0666
	directory mask = 0777
	read only = yes
	guest ok = yes 
```

**Comment by sergey-senozhatsky** [comment]
On (19/12/17 03:35), Andy Walsh wrote:
>    I have the share below via guest and while i can not copy/create files, i
>    can actually delete files/folders?
> 
>  [test]
>          path = /mnt/sda
>          create mask = 0666
>          directory mask = 0777
>          read only = yes
>          guest ok = yes

Good catch. I guess we should not set DELETE_ON_CLOSE when
CIFSD_SHARE_FLAG_READONLY | CIFSD_TREE_CONN_FLAG_READ_ONLY.

	-ss

**Comment by namjaejeon** [comment]
FIXED, Pushed it to the cifsd-next, Will inform when merging into the master.
Thanks Andy!

**Comment by namjaejeon** [comment]
@Andy2244 I will release v2.0.6 version and set tag also.
Please check it.
Thanks!

**Comment by Andy2244** [comment]
Checked 3.0.1, is fixed thanks.
