### ISSUE TITLE
use full names for release archives.

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/smbd#282]
The smbd and smbd-tools release archives both have the same name, confusing our default buildsystem.

Rename the releases so they end-up having distinct names: `smbd-3.0.1.tar.gz` and `smbd-tools-3.0.1.tar.gz` instead of both `v3.0.1.tar.gz`.

**Comment by namjaejeon** [comment]
I understood that git tag name is changed to smbd-v3.0.1 from v3.0.1. I changed it now. right ?

**Comment by Andy2244** [comment]
kinda the release file is actually named: `smbd-tools-smbd-tools-v3.0.1.tar.gz` and `smbd-smbd-v3.0.1.tar.gz` not sure why it doubles the names?

**Comment by namjaejeon** [comment]
Yes, I changed tag name from v3.0.1 to smbd-v3.0.1 as you raise a issue(look v3.0.1.tar.gz). When tag name was v3.0.1, It looks normal with smbd-3.0.1.tar.gz.

**Comment by Andy2244** [comment]
So what filename you get as download if you use the release link?
https://github.com/cifsd-team/smbd/archive/smbd-v3.0.1.tar.gz

**Comment by namjaejeon** [comment]
Understood... please check them again!

**Comment by Andy2244** [comment]
ok github tag releases are still weird as f...

The shown url is: `https://github.com/cifsd-team/smbd/archive/3.0.1.tar.gz`
It downloads: `smbd-3.0.1.tar.gz`

I found a other package and it constructs this url, which also works and is consistent...
`https://github.com/cifsd-team/smbd/archive/3.0.1/smbd-3.0.1.tar.gz`
