### ISSUE TITLE
small bug in endian handling

### ISSUE THREAD

**Issue by BrainSlayer** [cifsd-team/smbd#287]
https://github.com/cifsd-team/smbd/blob/a608ddfb71572d23615080adf3a0ab25e013bf85/smb1pdu.c#L2060

AndXCommand is u8 so cpu_to_le16(0xff) makes no sense and will turn the value to zero on big endian systems. this has been discovered by gcc compiler warning

**Comment by namjaejeon** [comment]
Ah, Good catch! Could you please send the patch to us(linux-cifsd-devel@lists.sourceforge.net) ? I will push your patch. If you can't it, Please tell me. I will direclty do it.

Thanks for your report!

**Comment by BrainSlayer** [comment]
@namjaejeon i can. i'm just busy with alot of things and have not created a fork yet. its just a one liner. i'm pretty sure you are able to insert rsp->AndXCommand = 0xff; by your self :-)

**Comment by namjaejeon** [comment]
Yup, I will.
Thanks!

**Comment by namjaejeon** [comment]
Pushed the patch to master branch.

please check the patch.
https://github.com/cifsd-team/smbd/commit/a7a8bad6e7be6a200f1610814a4cdaa53f65f50a

Thanks!

**Comment by BrainSlayer** [comment]
if course you can close issues which are known to be fixed/merged
