### ISSUE TITLE
length can run bellow zero which may cause stack corruption in follow up code

### ISSUE THREAD

**Issue by BrainSlayer** [cifsd-team/smbd#290]
https://github.com/cifsd-team/smbd/blob/d3227e73b9a705498e7c85ea218e69ec32a6e209/unicode.c#L269

the for loop checks only if len is non zero. but len-=charlen may let it run bellow zero, so the input buffer might run out of bounds until a undefined length and the returned length will be bigger than expected which may cause issues by the caller
so use len > 0 in this statement

**Comment by namjaejeon** [comment]
Pushed the patch to master (https://github.com/cifsd-team/smbd/commit/ff9beb2a13a47286bab45d784978c6a7ca0ad017)

Thanks!
